### ISSUE TITLE
Miscurled quotation marks

### ISSUE THREAD

**Issue by acabal** [drgrigg/anthony-trollope_barchester-towers#1]
Use this regex to find them: `\s‘[a-z]`

**Comment by drgrigg** [comment]
Hmmm, not sure about this one. Where a word is abbreviated by missing characters at the start of a word, it should lead with a RIGHT single quote, eg ’cause not ‘cause for “because”. In words like don’t, it’s a right single quote because the ‘o’ is missing. In ’cause, the ‘be’ is missing. Am I wrong?

There are a lot of incorrect usages in the Gutenberg texts.

**Comment by drgrigg** [comment]
Or am I assuming incorrectly what you are pointing at? Can you give some examples of what you think should be corrected?

**Comment by drgrigg** [comment]
Oh, hang on, I do see some which have LEFT single quotes which should be RIGHT single quotes. Now I get it!

**Comment by drgrigg** [comment]
The ones in Chapter 16 (baby talk) seem to be the only ones. Fixed them now. Sorry I got the wrong handle on it to start with.
